#!/bin/bash

# Install java / dependencies
sudo apt update && sudo apt full-upgrade -y
sudo apt install -y git build-essential cmake gcc-arm-linux-gnueabihf openjdk-21-jdk

# Enable ARM hard float architecture / install dependencies
sudo dpkg --add-architecture armhf && sudo apt update
sudo apt install -y libc6:armhf libncurses5:armhf libstdc++6:armhf

 # Open firewall ports and reload the fw
sudo ufw allow 16261/udp
sudo ufw allow 16262/udp
sudo ufw reload

# Clone and build Box64
git clone https://github.com/ptitSeb/box64.git
cd box64 && mkdir -p build && cd build
cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j$(nproc)
sudo make install
sudo cp box64 /usr/local/bin/
sudo systemctl restart systemd-binfmt
cd ../..

# Steamcmd setup
mkdir steamcmd && cd steamcmd
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
# Update steamcmd
./steamcmd.sh +quit > /dev/null

# Set up and download zomboid server
sudo mkdir -p /opt/zomboid-server/
sudo chown -R $USER:$USER /opt/zomboid-server/
./steamcmd.sh +force_install_dir /opt/zomboid-server/ +@sSteamCmdForcePlatformType linux +login anonymous +app_update 380870 -beta unstable validate +quit > /dev/null

# Fix up some dependencies and paths for server files
sudo ln -sf /opt/zomboid-server/linux64/steamclient.so /opt/zomboid-server/linux64/libsteam.so
sudo sed -i 's|LD_PRELOAD="${LD_PRELOAD}:${JSIG}" ./ProjectZomboid64 "$@"|LD_PRELOAD="${LD_PRELOAD}:${JSIG}" ./ProjectZomboid64 -cachedir=/opt/zomboid-server "$@"|' /opt/zomboid-server/start-server.sh

# Prompt user for manual config
read -p "Please start the server manually and set the password. Press Enter when that's done..."

# Set up zomboid as a systemd service
sudo tee /etc/systemd/system/zomboid-server.service > /dev/null <<'EOL'
[Unit]
Description=Project Zomboid Server
After=network.target

[Service]
User=root
WorkingDirectory=/opt/zomboid-server

# IMPORTANT: force data directory + prevent LD_PRELOAD issues

ExecStart=/opt/zomboid-server/start-server.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
source /usr/share/bash-completion/completions/systemctl
sudo systemctl enable zomboid-server && sudo systemctl start zomboid-server
